### ISSUE TITLE
[Feature] Allow cell selection while holding Ctrl.

### ISSUE THREAD

**Issue by xXleowXx** [doonfrs/trina_grid#75]
Hi, 
Thanks for your fantastic work.

I would much appreciate a feature that allows the selection of unconnected cells while holding CTRL in TrinaGridSelectingMode.cell.

![Image](https://github.com/user-attachments/assets/4ff3ac6e-f9d5-4cab-83c4-2fc4687655c9)

**Comment by DMouayad** [comment]
Hi @xXleowXx,
So we've made significant changes to the selection feature, it's not published yet But I'd appreciate any feedback on it.

version can be installed like this: in `pubspec.yaml`

```
 trina_grid:
    git:
      url: https://github.com/DMouayad/trina_grid.git
      ref: feat/new-selection-feature
```
